geography:
  data_dir: "../NZ_1918/data/geography"
  levels: [SGU, Province]
  hierarchy_file: "hierarchy.csv"

venues:
  data_dir: "../NZ_1918/data/venues"
  config_file: "../NZ_1918/NZ_yaml_files/venues_config.yaml"

population:
  type: "generated"
  data_dir: "../NZ_1918/data/population"
  demographics_male_file: "demography_male.csv"
  demographics_female_file: "demography_female.csv"

households:
  enabled: true
  data_dir: "../NZ_1918/data/households"
  data_file: "synthetic_households.csv"
  config_file: "../NZ_1918/NZ_yaml_files/yaml/households/households_config.yaml"
  strategy_file: "../NZ_1918/NZ_yaml_files/yaml/households/allocation_strategy.yaml"

timeline:
  enabled: true
  steps:
    - type: attribute
      config: "../NZ_1918/NZ_yaml_files/yaml/attributes/sector_assignment.yaml"
    - type: distributor
      config: "../NZ_1918/NZ_yaml_files/yaml/distributors/residence_distribution_config.yaml"
    - type: distributor
      config: "../NZ_1918/NZ_yaml_files/yaml/distributors/workplace_agricultural_distributor.yaml"
    - type: distributor
      config: "../NZ_1918/NZ_yaml_files/yaml/distributors/workplace_commercial_distributor.yaml"
    - type: distributor
      config: "../NZ_1918/NZ_yaml_files/yaml/distributors/workplace_domestic_distributor.yaml"
    - type: distributor
      config: "../NZ_1918/NZ_yaml_files/yaml/distributors/workplace_industrial_distributor.yaml"
    - type: distributor
      config: "../NZ_1918/NZ_yaml_files/yaml/distributors/workplace_professional_distributor.yaml"
    - type: distributor
      config: "../NZ_1918/NZ_yaml_files/yaml/distributors/workplace_transport_distributor.yaml"
    - type: distributor
      config: "../NZ_1918/NZ_yaml_files/yaml/distributors/workplace_indefinite_distributor.yaml"

serialization:
  enabled: true
  config_file: "../NZ_1918/NZ_yaml_files/yaml/serialization_config.yaml"
  output_dir: "output/NZ"
  filename: "nz_1918_world.h5"
  compression: "gzip"
